BUG: addItems() complains about postinstall-or-once:
> ERROR: Invalid type: postinstall-or-once:
And it should not be concerned with that; after we've determined that the item is not installed yet (so the -or-once part does not apply), this should be treated like any other postinstall: item, so translate the prefix into that.