deb+url: Report availability so that this item can be used with dummy:
> ERROR: Type deb+url: cannot be used as a dummy item; it does not report availability.