pip3: Robustness: Override a require-virtualenv = true user configuration
Normal users don't have the rights to install system-wide packages, and pip then falls back to a user-local installation. On a single-user system, that doesn't make much sense, and user installations should always be done in a project-specific virtual env. The above configuration (in ~/.config/pip/pip.conf) prevents this.
For _querying_ system-wide packages, no sudo is required, but that configuration also prevents the listing:
> ERROR: Could not find an activated virtualenv (required).
Override any user config via an environment variable override.